### ISSUE TITLE
deploy directory must be committed?

### ISSUE THREAD

**Issue by csrvermaak** [X1011/git-directory-deploy#15]
Hi

I've found this very useful trick to automatically deploy the contents of my deploy_folder as my gh-pages content. I've managed to get it working, but only when I add the deploy_folder to master.

If I don't add the deploy_folder to git, then there is no way for travis to access the files in the deploy_folder? Is this interpretation correct? Thus - to have travis run the deploy.cs, I do need to commit the deploy_folder contents, in my view. Please tell me if I am wrong in this?

Regards

**Comment by MoOx** [comment]
I think Travis clone repo in read only and that may be the reason why you have an issue. That's why some others solutions are cloning the repo (with write access using an encrypted github token) in another folder.

**Comment by csrvermaak** [comment]
Thank @MoOx. My question is - how can travis clone the repo, if the files in the deploy_folder is not committed?

**Comment by MoOx** [comment]
The thing is to change the repo reference using a token.

Example here
- https://github.com/putaindecode/putaindecode.fr/blob/f8490b362b4186b271757b984ac4fc50618eea8d/scripts/deploy-to-gh-pages.sh#L10-L29
- https://github.com/putaindecode/putaindecode.fr/blob/f8490b362b4186b271757b984ac4fc50618eea8d/package.json#L84

**Comment by MoOx** [comment]
You will also need a encrypted github token https://github.com/putaindecode/putaindecode.fr/blob/f8490b362b4186b271757b984ac4fc50618eea8d/.travis.yml#L41

**Comment by csrvermaak** [comment]
Thanks @MoOx - I'm an noob, and I think I am perhaps not asking my question correctly, out of ignorance. Please forgive me. 

My question is this - I have cloned my repository to C:\reponame\ and have run some scripts to update my C:\reponame\out\index.html file. (This file is what will become my GitHub-Pages site)

The \out\ folder contents is not under version control. If I now commit & sync, the index.html file will be ONLY on my C:\, and nowhere else, so travis cannot access it. 

However, if I add the \out\ folder contents, commit and sync, then travis can run the deploy script on the files, and perform the neat little trick to overwrite the gh-pages branch.

Am I correct in my understanding?

Once again, apologies if this is a silly question.

**Comment by X1011** [comment]
Hi @csrvermaak! If `\out\` is committed to your repo, you can push it to `gh-pages` with a simple [`git subtree push`](https://github.com/yeoman/yeoman.github.io/blob/source/app/learning/deployment.md#git-subtree-command) command, and you don't even need this script.

The whole reason I wrote this script was so that I didn't have to commit the deploy folder to my repo. You could do the same, but you will have to generate `\out\` as part of your Travis build, rather than doing it on your own computer.

Feel free to reopen this issue if you have any further questions.
