### ISSUE TITLE
error: the following files have changes staged in the index

### ISSUE THREAD

**Issue by webjay** [X1011/git-directory-deploy#4]
I'm getting this error from the command `git --work-tree dist rm -r '*'`, would you recommend `--cached` or `-f`?

    error: the following files have changes staged in the index
    (use --cached to keep the file, or -f to force removal)

My guess is that it is caused by the branch having existed previously?

Btw, thanks for a great script. I use it at [journster.com](http://www.journster.com/)

**Comment by X1011** [comment]
Ah, ok. there actually is a check for uncommitted changes, but it currently doesn't apply to setup. i'll fix that.

thanks for the kind words. i'm glad to see my little script getting around.

**Comment by raine** [comment]
I had this issue as well.

I had to remove dist, do `./deploy.sh -s` then add a dummy `dist` folder with `.gitignore` to gh-pages and make a commit. After that `./deploy.sh` would work in master.

**Comment by X1011** [comment]
hi @raine. if i understand correctly, when you try to run the setup while you have a `dist/` folder that's not `.gitignore`'d, you get an error about untracked files. this sounds like a separate issue. i'll open another issue for this.
